
name: Docker trysec_BlueLotus_XSSReceiver Build

on:
  push

jobs:
  Docker_trysec_BlueLotus_XSSReceiver_Build:
    name: Docker trysec_BlueLotus_XSSReceiver Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/BlueLotus_XSSReceiver
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dnslog:trysec_bluelotus_xssreceiver
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dnslog:trysec_bluelotus_xssreceiver.cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dnslog:trysec_bluelotus_xssreceiver.cache,mode=max
